Use release builds of non-ChickenBones dependencies
-- The dev/deobf builds use older MCP mappings, so they throw
NoSuchMethodError/NoSuchFieldErrors
- Use custom builds of ChickenBones dependencies using the same MCP
mappings version manually placed in the Gradle cache
-- CodeChickenLib and CodeChickenCore need to be deobf builds to
deobfuscate the other mods at runtime